###############################################################################
#created on: 18 feb. 2009
package webtemplates

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.content.*
import org.jahia.data.search.*
import org.jahia.params.*
import org.apache.log4j.Logger

expander rules.dsl

#declare any global variables here
global ProcessingContext processingContext

###############################################################################
