###############################################################################
package org.jahia.modules.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.apache.log4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider
###############################################################################

rule "Tagging"
   when
       A property j:newTag has been set on a node
        - the node has the type jmix:tagged
   then
       Tag the node with the propertyValueAsString
end

rule "Menu - create page"
    when
        A new node is created
         - it has the type jnt:page
    then
        Create a link in the navigation menu
end

rule "Menu - delete page"
    when
        A node is deleted
    then
        Delete associated links
end
