println '<!DOCTYPE html>'
println '<html>'
println '<head>'
println '    <meta charset="utf-8">'
println '    <meta name="robots" content="noindex, nofollow"/>'
println '    <link rel="stylesheet" href="' + renderContext.getRequest().getContextPath() + '/css/admin-front.css" type="text/css"/>'
println '    <title>Preview</title>'
println '</head>'
println '<body class="login">'
println '   <div class="row-fluid login-wrapper">'
println '   <img class="logo" alt="jahia" src="' + renderContext.getRequest().getContextPath() + '/css/images/jahia-logo-white.png">'
println '       <div class="span4 box error-box">'
println '           <div class="content-wrap">'
println '               <h1 class="message-big">' + i18n.get("label.preview") + '</h1>'
println '        	    <p>' + i18n.get("label.preview.markedForDeletion") + '</p>'
println '               <br class="clearFloat" />'
println '           </div>'
println '       </div>'
println '   </div>'
println '</body>'
println '</html>'