drop table jr_default_BUNDLE cascade constraints;
drop table jr_default_REFS cascade constraints;
drop table jr_default_BINVAL cascade constraints;
drop table jr_default_NAMES cascade constraints;
drop table jr_v_BUNDLE cascade constraints;
drop table jr_v_REFS cascade constraints;
drop table jr_v_BINVAL cascade constraints;
drop table jr_v_NAMES cascade constraints;
drop table jr_fsdefault_FSENTRY cascade constraints;
drop table jr_fsg_FSENTRY cascade constraints;
drop table jr_fsv_FSENTRY cascade constraints;
drop table JOURNAL cascade constraints;
drop table GLOBAL_REVISION cascade constraints;
drop table LOCAL_REVISIONS cascade constraints;
drop sequence jr_default_seq_names_id;
drop sequence jr_v_seq_names_id;
