###############################################################################
package org.jahia.modules.feedimporter.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.slf4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider
###############################################################################

rule "Synchronize feed"
   salience 25
   when
       A property syncro has been set on a node
        - the node has the type jnt:feed
   then
       Execute the action "getfeed" at syncro on the node
end

#rule "Auto Publish News Nodes"
#   salience -50
#   when
#       A new node is created
#        - the node has the type jnt:newsMLItem
#   then
#       Publish the node
#end

#rule "Auto Start Workflow On News Nodes"
#   salience -50
#   when
#       A property contentUpdated has been set on a node
#        - the node has the type jnt:newsMLItem
#   then
#       Start the workflow "2-step-publication" from "jBPM" on the node
#end
