<div class='grid_10'><!--start grid_10-->
  <h2>600px Position #1</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sed sodales sem. Nullam neque nulla, iaculis sed feugiat a, dapibus ac magna. Praesent ut eros metus, eu semper velit. Quisque vestibulum nunc eu enim commodo bibendum eu eget sem. Aenean elit nunc, commodo id mattis vel, euismod eget odio. Donec augue ligula, laoreet at vestibulum quis, dictum nec sapien. Sed non orci ut massa auctor malesuada. Nam blandit lectus ut magna rutrum gravida. Curabitur auctor tincidunt porta. Phasellus dictum massa et neque semper sed interdum nunc elementum. Fusce ut urna ante, at facilisis augue. Suspendisse augue enim, scelerisque id sodales sed, congue in justo. Praesent in nisl neque. Etiam ante urna, posuere nec blandit sed, imperdiet nec lorem. Aenean vel erat libero. Duis sagittis fringilla eros. Proin mattis semper tellus, quis dignissim odio placerat quis.

Integer a nibh magna, non vehicula est. Quisque lectus urna, accumsan quis tristique at, pellentesque sit amet est. Nunc volutpat ullamcorper velit, sit amet dapibus justo lacinia nec. Etiam dignissim condimentum fermentum. Donec eget ligula vel felis dapibus semper. Phasellus congue sapien ut velit scelerisque vitae molestie velit tempor. Nam imperdiet molestie mi, at fringilla arcu commodo in. Maecenas cursus dapibus diam, non consequat urna interdum et. Nullam in tellus sed magna varius eleifend sed et nulla. Etiam ut nibh augue. Curabitur nibh est, ultricies vitae vestibulum ut, sagittis ut est. Proin ut odio magna. Ut iaculis suscipit cursus. Pellentesque pharetra interdum congue. Integer suscipit tincidunt velit quis adipiscing. Fusce at justo sit amet nisl feugiat ultrices. Praesent magna dui, viverra nec varius sed, dapibus sit amet neque. Nulla dignissim dignissim lectus vehicula posuere. </p>
<div class='clear'></div></div><!--stop grid_10-->

<div class='grid_6'><!--start grid_6-->
  <h2>360px Position #2</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sed sodales sem. Nullam neque nulla, iaculis sed feugiat a, dapibus ac magna. Praesent ut eros metus, eu semper velit. Quisque vestibulum nunc eu enim commodo bibendum eu eget sem. Aenean elit nunc, commodo id mattis vel, euismod eget odio. Donec augue ligula, laoreet at vestibulum quis, dictum nec sapien. Sed non orci ut massa auctor malesuada. Nam blandit lectus ut magna rutrum gravida. Curabitur auctor tincidunt porta. Phasellus dictum massa et neque semper sed interdum nunc elementum. Fusce ut urna ante, at facilisis augue. Suspendisse augue enim, scelerisque id sodales sed, congue in justo. Praesent in nisl neque. Etiam ante urna, posuere nec blandit sed, imperdiet nec lorem. Aenean vel erat libero. Duis sagittis fringilla eros. Proin mattis semper tellus, quis dignissim odio placerat quis. </p>
  <div class='clear'></div></div><!--stop grid_6-->

