    drop table jahia_nodetypes_provider;

    create table jahia_nodetypes_provider (
        id integer generated by default as identity,
        cndFile clob not null,
        filename varchar(255) not null,
        primary key (id)
    );

    create index jahia_nodetypes_provider_ix1 on jahia_nodetypes_provider (filename);
