
    drop table jahia_external_mapping;

    drop table jahia_external_provider_id;

    create table jahia_external_mapping (
        internalUuid varchar(36) not null,
        externalId clob(255) not null,
        externalIdHash integer,
        providerKey varchar(255) not null,
        primary key (internalUuid)
    );

    create table jahia_external_provider_id (
        id integer generated by default as identity,
        providerKey varchar(255) not null,
        primary key (id)
    );

    create index jahia_external_mapping_index1 on jahia_external_mapping (externalIdHash, providerKey);

    create index jahia_external_provider_id_ix1 on jahia_external_provider_id (providerKey);
