###############################################################################
package org.jahia.modules.feedimporter.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.apache.log4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider
###############################################################################

rule "Synchronize feed"
   when
       A property syncro has been set on a node
        - the node has the type jnt:feed
   then
       Execute the action "getfeed" at syncro on the node
end

rule "Auto Publish News Nodes"
   when
       A new node is created
        - the node has the type jnt:newsMLItem
   then
       Publish the node
end

rule "Auto Start Workflow On News Nodes"
   when
       A property contentUpdated has been set on a node
        - the node has the type jnt:newsMLItem
   then
       Start the workflow "2-step-publication" from "jBPM" on the node
end
