###############################################################################
package org.jahia.modules.feedimporter.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.apache.log4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider
###############################################################################

rule "Synchronize feed"
   when
       A property syncro has been set on a node
        - the node has the type jnt:feed
   then
       Execute the action "getfeed" with syncro on the node
end
