drop table seq_grps;
create table seq_grps ( next_val bigint );
insert into seq_grps values ( 1 );
drop table seq_link;
create table seq_link ( next_val bigint );
insert into seq_link values ( 1 );
drop table seq_pwd_policies;
create table seq_pwd_policies ( next_val bigint );
insert into seq_pwd_policies values ( 1 );
drop table seq_pwd_policy_rules;
create table seq_pwd_policy_rules ( next_val bigint );
insert into seq_pwd_policy_rules values ( 1 );
drop table seq_pwd_policy_rule_params;
create table seq_pwd_policy_rule_params ( next_val bigint );
insert into seq_pwd_policy_rule_params values ( 1 );
drop table seq_users;
create table seq_users ( next_val bigint );
insert into seq_users values ( 1 );
drop table seq_version;
create table seq_version ( next_val bigint );
insert into seq_version values ( 1 );
drop table seq_installedpatch;
create table seq_installedpatch ( next_val bigint );
insert into seq_installedpatch values ( 1 );
drop table seq_subscriptions;
create table seq_subscriptions ( next_val bigint );
insert into seq_subscriptions values ( 1 );
