###############################################################################
package org.jahia.modules.search.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.render.*
import org.jahia.services.search.*
import org.slf4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global Logger logger
global SearchURLService urlService
global RenderContext renderContext
###############################################################################

