###############################################################################
package org.jahia.modules.docspace.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.slf4j.Logger
import java.util.Date
import org.jahia.services.content.*

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider
###############################################################################

rule "Create docspace"
   when
       A new node is created
	   - the node has the type jmix:docspace
   then
       Assign permissions "re---" on the node to the group "users"
       Assign permissions "rewap" on the node to the current user
end

rule "Mark node as docspace file"
    salience 10
	when
		A new node is created
			- the node has the type jnt:file
        The node has a parent
             - it has the extension type jmix:docspace
	then
        Log "Tag file as docspace file (jmix:docspaceFile) for node " + node.getPath()
        Add the type jmix:docspaceFile
        Add the type jmix:comments
        Create a new node post of type jnt:post under the node.getNode("comments")
        Set the property content of the post with the value "file uploaded"
end

rule "Update file in docspace"
   when
      A file content has been modified
	   - it has the extension type jmix:docspaceFile
        The node has a parent
             - it has the extension type jmix:docspace
   then
       Create a new node post of type jnt:post under the node.getNode("comments")
       Set the property content of the post with the value "file updated"
end