drop table seq_acl;
create table seq_acl ( next_val numeric(19,0) );
insert into seq_acl values ( 1 );
drop table seq_audit_log;
create table seq_audit_log ( next_val numeric(19,0) );
insert into seq_audit_log values ( 1 );
drop table seq_ctn_def;
create table seq_ctn_def ( next_val numeric(19,0) );
insert into seq_ctn_def values ( 1 );
drop table seq_ctn_def_properties;
create table seq_ctn_def_properties ( next_val numeric(19,0) );
insert into seq_ctn_def_properties values ( 1 );
drop table seq_ctn_entries;
create table seq_ctn_entries ( next_val numeric(19,0) );
insert into seq_ctn_entries values ( 1 );
drop table seq_ctn_lists;
create table seq_ctn_lists ( next_val numeric(19,0) );
insert into seq_ctn_lists values ( 1 );
drop table seq_fields_data;
create table seq_fields_data ( next_val numeric(19,0) );
insert into seq_fields_data values ( 1 );
drop table seq_fields_def;
create table seq_fields_def ( next_val numeric(19,0) );
insert into seq_fields_def values ( 1 );
drop table seq_grps;
create table seq_grps ( next_val numeric(19,0) );
insert into seq_grps values ( 1 );
drop table seq_link;
create table seq_link ( next_val numeric(19,0) );
insert into seq_link values ( 1 );
drop table seq_nstep_workflow;
create table seq_nstep_workflow ( next_val numeric(19,0) );
insert into seq_nstep_workflow values ( 1 );
drop table seq_nstep_workflowhistory;
create table seq_nstep_workflowhistory ( next_val numeric(19,0) );
insert into seq_nstep_workflowhistory values ( 1 );
drop table seq_nstep_workflowinstance;
create table seq_nstep_workflowinstance ( next_val numeric(19,0) );
insert into seq_nstep_workflowinstance values ( 1 );
drop table seq_nstep_workflowstep;
create table seq_nstep_workflowstep ( next_val numeric(19,0) );
insert into seq_nstep_workflowstep values ( 1 );
drop table seq_nstep_workflowuser;
create table seq_nstep_workflowuser ( next_val numeric(19,0) );
insert into seq_nstep_workflowuser values ( 1 );
drop table seq_pages_data;
create table seq_pages_data ( next_val numeric(19,0) );
insert into seq_pages_data values ( 1 );
drop table seq_pages_def;
create table seq_pages_def ( next_val numeric(19,0) );
insert into seq_pages_def values ( 1 );
drop table seq_pwd_policies;
create table seq_pwd_policies ( next_val numeric(19,0) );
insert into seq_pwd_policies values ( 1 );
drop table seq_pwd_policy_rules;
create table seq_pwd_policy_rules ( next_val numeric(19,0) );
insert into seq_pwd_policy_rules values ( 1 );
drop table seq_pwd_policy_rule_params;
create table seq_pwd_policy_rule_params ( next_val numeric(19,0) );
insert into seq_pwd_policy_rule_params values ( 1 );
drop table seq_retrule;
create table seq_retrule ( next_val numeric(19,0) );
insert into seq_retrule values ( 1 );
drop table seq_retrule_range;
create table seq_retrule_range ( next_val numeric(19,0) );
insert into seq_retrule_range values ( 1 );
drop table seq_retruledef;
create table seq_retruledef ( next_val numeric(19,0) );
insert into seq_retruledef values ( 1 );
drop table seq_site_lang_list;
create table seq_site_lang_list ( next_val numeric(19,0) );
insert into seq_site_lang_list values ( 1 );
drop table seq_site_lang_maps;
create table seq_site_lang_maps ( next_val numeric(19,0) );
insert into seq_site_lang_maps values ( 1 );
drop table seq_sites;
create table seq_sites ( next_val numeric(19,0) );
insert into seq_sites values ( 1 );
drop table seq_users;
create table seq_users ( next_val numeric(19,0) );
insert into seq_users values ( 1 );
drop table seq_savedsearch;
create table seq_savedsearch ( next_val numeric(19,0) );
insert into seq_savedsearch values ( 1 );
drop table seq_version;
create table seq_version ( next_val numeric(19,0) );
insert into seq_version values ( 1 );
drop table seq_installedpatch;
create table seq_installedpatch ( next_val numeric(19,0) );
insert into seq_installedpatch values ( 1 );
drop table seq_subscriptions;
create table seq_subscriptions ( next_val numeric(19,0) );
insert into seq_subscriptions values ( 1 );
