IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[FK_JAHIA_QRTZ_JOB_LISTENERS_JAHIA_QRTZ_JOB_DETAILS]') AND OBJECTPROPERTY(id, N'ISFOREIGNKEY') = 1)
ALTER TABLE [JAHIA_QRTZ_JOB_LISTENERS] DROP CONSTRAINT FK_JAHIA_QRTZ_JOB_LISTENERS_JAHIA_QRTZ_JOB_DETAILS
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[FK_JAHIA_QRTZ_TRIGGERS_JAHIA_QRTZ_JOB_DETAILS]') AND OBJECTPROPERTY(id, N'ISFOREIGNKEY') = 1)
ALTER TABLE [JAHIA_QRTZ_TRIGGERS] DROP CONSTRAINT FK_JAHIA_QRTZ_TRIGGERS_JAHIA_QRTZ_JOB_DETAILS
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[FK_JAHIA_QRTZ_CRON_TRIGGERS_JAHIA_QRTZ_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISFOREIGNKEY') = 1)
ALTER TABLE [JAHIA_QRTZ_CRON_TRIGGERS] DROP CONSTRAINT FK_JAHIA_QRTZ_CRON_TRIGGERS_JAHIA_QRTZ_TRIGGERS
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[FK_JAHIA_QRTZ_SIMPLE_TRIGGERS_JAHIA_QRTZ_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISFOREIGNKEY') = 1)
ALTER TABLE [JAHIA_QRTZ_SIMPLE_TRIGGERS] DROP CONSTRAINT FK_JAHIA_QRTZ_SIMPLE_TRIGGERS_JAHIA_QRTZ_TRIGGERS
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[FK_JAHIA_QRTZ_TRIGGER_LISTENERS_JAHIA_QRTZ_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISFOREIGNKEY') = 1)
ALTER TABLE [JAHIA_QRTZ_TRIGGER_LISTENERS] DROP CONSTRAINT FK_JAHIA_QRTZ_TRIGGER_LISTENERS_JAHIA_QRTZ_TRIGGERS
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_CALENDARS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_CALENDARS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_CRON_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_CRON_TRIGGERS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_BLOB_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_BLOB_TRIGGERS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_FIRED_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_FIRED_TRIGGERS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_PAUSED_TRIGGER_GRPS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_PAUSED_TRIGGER_GRPS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_SCHEDULER_STATE]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_SCHEDULER_STATE]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_LOCKS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_LOCKS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_JOB_DETAILS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_JOB_DETAILS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_JOB_LISTENERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_JOB_LISTENERS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_SIMPLE_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_SIMPLE_TRIGGERS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_TRIGGER_LISTENERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_TRIGGER_LISTENERS]
;

IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'[JAHIA_QRTZ_TRIGGERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [JAHIA_QRTZ_TRIGGERS]
;

CREATE TABLE [JAHIA_QRTZ_CALENDARS] (
  [CALENDAR_NAME] [NVARCHAR] (80)  NOT NULL ,
  [CALENDAR] [IMAGE] NOT NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_CRON_TRIGGERS] (
  [TRIGGER_NAME] [NVARCHAR] (80)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [CRON_EXPRESSION] [NVARCHAR] (80)  NOT NULL ,
  [TIME_ZONE_ID] [NVARCHAR] (80)
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_FIRED_TRIGGERS] (
  [ENTRY_ID] [NVARCHAR] (95)  NOT NULL ,
  [TRIGGER_NAME] [NVARCHAR] (80)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [IS_VOLATILE] [NVARCHAR] (1)  NOT NULL ,
  [INSTANCE_NAME] [NVARCHAR] (80)  NOT NULL ,
  [FIRED_TIME] [BIGINT] NOT NULL ,
  [PRIORITY] [INTEGER] NOT NULL ,
  [STATE] [NVARCHAR] (16)  NOT NULL,
  [JOB_NAME] [NVARCHAR] (80)  NULL ,
  [JOB_GROUP] [NVARCHAR] (80)  NULL ,
  [IS_STATEFUL] [NVARCHAR] (1)  NULL ,
  [REQUESTS_RECOVERY] [NVARCHAR] (1)  NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_PAUSED_TRIGGER_GRPS] (
  [TRIGGER_GROUP] [NVARCHAR] (80)  NOT NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_SCHEDULER_STATE] (
  [INSTANCE_NAME] [NVARCHAR] (80)  NOT NULL ,
  [LAST_CHECKIN_TIME] [BIGINT] NOT NULL ,
  [CHECKIN_INTERVAL] [BIGINT] NOT NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_LOCKS] (
  [LOCK_NAME] [NVARCHAR] (40)  NOT NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_JOB_DETAILS] (
  [JOB_NAME] [NVARCHAR] (80)  NOT NULL ,
  [JOB_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [DESCRIPTION] [NVARCHAR] (120) NULL ,
  [JOB_CLASS_NAME] [NVARCHAR] (128)  NOT NULL ,
  [IS_DURABLE] [NVARCHAR] (1)  NOT NULL ,
  [IS_VOLATILE] [NVARCHAR] (1)  NOT NULL ,
  [IS_STATEFUL] [NVARCHAR] (1)  NOT NULL ,
  [REQUESTS_RECOVERY] [NVARCHAR] (1)  NOT NULL ,
  [JOB_DATA] [IMAGE] NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_JOB_LISTENERS] (
  [JOB_NAME] [NVARCHAR] (80)  NOT NULL ,
  [JOB_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [JOB_LISTENER] [NVARCHAR] (80)  NOT NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_SIMPLE_TRIGGERS] (
  [TRIGGER_NAME] [NVARCHAR] (80)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [REPEAT_COUNT] [BIGINT] NOT NULL ,
  [REPEAT_INTERVAL] [BIGINT] NOT NULL ,
  [TIMES_TRIGGERED] [BIGINT] NOT NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_BLOB_TRIGGERS] (
  [TRIGGER_NAME] [NVARCHAR] (80)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [BLOB_DATA] [IMAGE] NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_TRIGGER_LISTENERS] (
  [TRIGGER_NAME] [NVARCHAR] (80)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [TRIGGER_LISTENER] [NVARCHAR] (80)  NOT NULL
) ON [PRIMARY]
;

CREATE TABLE [JAHIA_QRTZ_TRIGGERS] (
  [TRIGGER_NAME] [NVARCHAR] (80)  NOT NULL ,
  [TRIGGER_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [JOB_NAME] [NVARCHAR] (80)  NOT NULL ,
  [JOB_GROUP] [NVARCHAR] (80)  NOT NULL ,
  [IS_VOLATILE] [NVARCHAR] (1)  NOT NULL ,
  [DESCRIPTION] [NVARCHAR] (120) NULL ,
  [NEXT_FIRE_TIME] [BIGINT] NULL ,
  [PREV_FIRE_TIME] [BIGINT] NULL ,
  [PRIORITY] [INTEGER] NULL ,
  [TRIGGER_STATE] [NVARCHAR] (16)  NOT NULL ,
  [TRIGGER_TYPE] [NVARCHAR] (8)  NOT NULL ,
  [START_TIME] [BIGINT] NOT NULL ,
  [END_TIME] [BIGINT] NULL ,
  [CALENDAR_NAME] [NVARCHAR] (80)  NULL ,
  [MISFIRE_INSTR] [SMALLINT] NULL ,
  [JOB_DATA] [IMAGE] NULL
) ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_CALENDARS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_CALENDARS] PRIMARY KEY  CLUSTERED
  (
    [CALENDAR_NAME]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_CRON_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_CRON_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_FIRED_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_FIRED_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [ENTRY_ID]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_PAUSED_TRIGGER_GRPS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_PAUSED_TRIGGER_GRPS] PRIMARY KEY  CLUSTERED
  (
    [TRIGGER_GROUP]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_SCHEDULER_STATE] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_SCHEDULER_STATE] PRIMARY KEY  CLUSTERED
  (
    [INSTANCE_NAME]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_LOCKS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_LOCKS] PRIMARY KEY  CLUSTERED
  (
    [LOCK_NAME]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_JOB_DETAILS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_JOB_DETAILS] PRIMARY KEY  CLUSTERED
  (
    [JOB_NAME],
    [JOB_GROUP]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_JOB_LISTENERS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_JOB_LISTENERS] PRIMARY KEY  CLUSTERED
  (
    [JOB_NAME],
    [JOB_GROUP],
    [JOB_LISTENER]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_SIMPLE_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_SIMPLE_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_TRIGGER_LISTENERS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_TRIGGER_LISTENERS] PRIMARY KEY  CLUSTERED
  (
    [TRIGGER_NAME],
    [TRIGGER_GROUP],
    [TRIGGER_LISTENER]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_JAHIA_QRTZ_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  )  ON [PRIMARY]
;

ALTER TABLE [JAHIA_QRTZ_CRON_TRIGGERS] ADD
  CONSTRAINT [FK_JAHIA_QRTZ_CRON_TRIGGERS_JAHIA_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [JAHIA_QRTZ_TRIGGERS] (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE
;

ALTER TABLE [JAHIA_QRTZ_JOB_LISTENERS] ADD
  CONSTRAINT [FK_JAHIA_QRTZ_JOB_LISTENERS_JAHIA_QRTZ_JOB_DETAILS] FOREIGN KEY
  (
    [JOB_NAME],
    [JOB_GROUP]
  ) REFERENCES [JAHIA_QRTZ_JOB_DETAILS] (
    [JOB_NAME],
    [JOB_GROUP]
  ) ON DELETE CASCADE
;

ALTER TABLE [JAHIA_QRTZ_SIMPLE_TRIGGERS] ADD
  CONSTRAINT [FK_JAHIA_QRTZ_SIMPLE_TRIGGERS_JAHIA_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [JAHIA_QRTZ_TRIGGERS] (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE
;

ALTER TABLE [JAHIA_QRTZ_TRIGGER_LISTENERS] ADD
  CONSTRAINT [FK_JAHIA_QRTZ_TRIGGER_LISTENERS_JAHIA_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [JAHIA_QRTZ_TRIGGERS] (
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE
;

ALTER TABLE [JAHIA_QRTZ_TRIGGERS] ADD
  CONSTRAINT [FK_JAHIA_QRTZ_TRIGGERS_JAHIA_QRTZ_JOB_DETAILS] FOREIGN KEY
  (
    [JOB_NAME],
    [JOB_GROUP]
  ) REFERENCES [JAHIA_QRTZ_JOB_DETAILS] (
    [JOB_NAME],
    [JOB_GROUP]
  )
;

INSERT INTO [JAHIA_QRTZ_LOCKS] VALUES('TRIGGER_ACCESS');
INSERT INTO [JAHIA_QRTZ_LOCKS] VALUES('JOB_ACCESS');
INSERT INTO [JAHIA_QRTZ_LOCKS] VALUES('CALENDAR_ACCESS');
INSERT INTO [JAHIA_QRTZ_LOCKS] VALUES('STATE_ACCESS');
INSERT INTO [JAHIA_QRTZ_LOCKS] VALUES('MISFIRE_ACCESS');

CREATE INDEX IDX_QRTZ_JD_JOB_GROUP ON JAHIA_QRTZ_JOB_DETAILS(JOB_GROUP);
CREATE INDEX IDX_QRTZ_JD_REQ_RECOVERY ON JAHIA_QRTZ_JOB_DETAILS(REQUESTS_RECOVERY);

CREATE INDEX IDX_QRTZ_FT_TRIG_NAME ON JAHIA_QRTZ_FIRED_TRIGGERS(TRIGGER_NAME);
CREATE INDEX IDX_QRTZ_FT_TRIG_GROUP ON JAHIA_QRTZ_FIRED_TRIGGERS(TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_FT_TRIG_N_G ON JAHIA_QRTZ_FIRED_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_FT_TRIG_VOLATILE ON JAHIA_QRTZ_FIRED_TRIGGERS(IS_VOLATILE);
CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON JAHIA_QRTZ_FIRED_TRIGGERS(INSTANCE_NAME);
CREATE INDEX IDX_QRTZ_FT_JOB_NAME ON JAHIA_QRTZ_FIRED_TRIGGERS(JOB_NAME);
CREATE INDEX IDX_QRTZ_FT_JOB_GROUP ON JAHIA_QRTZ_FIRED_TRIGGERS(JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_JOB_STATEFUL ON JAHIA_QRTZ_FIRED_TRIGGERS(IS_STATEFUL);
CREATE INDEX IDX_QRTZ_FT_JOB_REQ_RECOVERY ON JAHIA_QRTZ_FIRED_TRIGGERS(REQUESTS_RECOVERY);

CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON JAHIA_QRTZ_TRIGGERS(NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_STATE ON JAHIA_QRTZ_TRIGGERS(TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NF_ST ON JAHIA_QRTZ_TRIGGERS(TRIGGER_STATE,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_GROUP ON JAHIA_QRTZ_TRIGGERS(TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_T_VOLATILE ON JAHIA_QRTZ_TRIGGERS(IS_VOLATILE);
