drop sequence seq_pwd_policies;
create sequence seq_pwd_policies start 1 increment 20;
drop sequence seq_pwd_policy_rules;
create sequence seq_pwd_policy_rules start 1 increment 20;
drop sequence seq_pwd_policy_rule_params;
create sequence seq_pwd_policy_rule_params start 1 increment 20;
drop sequence seq_version;
create sequence seq_version start 1 increment 20;
drop sequence seq_installedpatch;
create sequence seq_installedpatch start 1 increment 20;
drop sequence seq_contenthistory;
create sequence seq_contenthistory start 1 increment 20;
