###############################################################################
#created on: 17 oct. 2008
package testtemplates

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.JCRStoreProvider
import javax.jcr.observation.Event
import org.apache.log4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global Logger logger
global JCRStoreProvider provider

###############################################################################

rule "New page rule test"
    when
        A new node "maincontent" is created
        The node has a parent
             - it has the type test_templates:rules
 then
#        Create a new node myFirstMainContent of type jnt:mainContentContainer under the node
#        Set the property mainContentTitle of the myFirstMainContent with the name of the current user
		Log "rules page created, main content created !"
end
