Anthracite.dictionary.set("DE", {
    'autoRefresh': 'automatische Aktualisierung',
    'jobs': 'Aufgaben',
    'zeroTasks': 'Dashboard öffnen',
    'singleTask': 'Dashboard (%n% Aufgabe)',
    'multipleTasks': 'Dashboard (%n% Aufgaben)',
    'workflowType': '%n% Workflow:',
    'chooseWorkflowType': 'Wählen Sie einen Workflow für %n%:',
    'filterField': 'Filter',
    'sortBy': 'Sortieren nach',
    'search': 'Suche %n%',
    'languageField': 'Alle Sprachen',
    'fromDate': 'Von ...',
    'toDate': 'bis ...',
    'dateRange': 'Datumsbereich',
    'dateAnyTime': 'Jederzeit',
    'dateCustom': 'Zeitspanne',
    'dateCustomLabel': 'Zeitspanne ...',
    'dateType': 'Nach %n% Datum',
    'allMetadata': 'Alle Metadaten',
    'ignoreMetadata': 'Metadaten ignorieren',
    'metaLabel': 'Meta: %n%',
    'cancel': 'Abbrechen',
    'create': 'Erstellen',
    'save': 'Speichern',
    'backgroundJobs': 'Hintergrund-Tasks',
    'filterContent': 'Content filtern',

    'previewPage': 'Vorschau',
    'previewSingleSelection': 'Vorschau',
    'previewMultipleSelection': 'Vorschau',

    'publishPage': 'Veröffentlichen',
    'publishSingleSelection': 'Veröffentlichen',
    'publishMultipleSelection': 'Veröffentlichen',

    'optionsPage': 'Seiten-Optionen',
    'optionsSingleSelection': '{{node}} Optionen',
    'optionsMultipleSelection': '{{count}} ausgewählte Inhalte',

    'pickerTitle-default': 'File Picker',
    'pickerTitle-imagepicker': jahia_gwt_messages.label_imagepicker,
    'pickerTitle-editoriallinkpicker': jahia_gwt_messages.label_editorialpicker,
    'pickerTitle-filemanager-anthracite': jahia_gwt_messages.label_filemanager_title,
    'pickerTitle-editorialcontentmanager-anthracite': jahia_gwt_messages.label_editorialcontentmanager_title,
    'pickerTitle-portletmanager-anthracite': jahia_gwt_messages.label_portletmanager_title,
    'pickerTitle-repositoryexplorer-anthracite': jahia_gwt_messages.label_repositoryexplorer_title,
    'pickerTitle-categorymanager-anthracite': jahia_gwt_messages.label_categorymanager_title,
    'pickerTitle-sitemanager-anthracite': jahia_gwt_messages.label_sitemanager_title
});

Anthracite.dictionary.set("EN", {
    'autoRefresh': 'Auto refresh',
    'jobs': 'Jobs',
    'zeroTasks': 'Open Dashboard',
    'singleTask': 'Dashboard (%n% task)',
    'multipleTasks': 'Dashboard (%n% tasks)',
    'workflowType': '%n% Workflow:',
    'chooseWorkflowType': 'Choose a workflow for %n%:',
    'filterField': 'Filter',
    'sortBy': 'Sort By',
    'search': 'Search %n%',
    'languageField': 'All Languages',
    'fromDate': 'From ...',
    'toDate': 'To ...',
    'dateRange': 'Date Range',
    'dateAnyTime': 'Any time',
    'dateCustom': 'Time range',
    'dateCustomLabel': 'Time range ...',
    'dateType': 'By %n% date',
    'allMetadata': 'All metadata',
    'ignoreMetadata': 'Ignore metadata',
    'metaLabel': 'Meta: %n%',
    'cancel': 'Cancel',
    'create': 'Create',
    'save': 'Save',
    'filterContent': 'Filter Content',
    'backgroundJobs': 'Background Jobs',

    'previewPage': 'Preview',
    'previewSingleSelection': 'Preview',
    'previewMultipleSelection': 'Preview',

    'publishPage': 'Publish',
    'publishSingleSelection': 'Publish',
    'publishMultipleSelection': 'Publish',

    'optionsPage': 'Page Options',
    'optionsSingleSelection': '{{node}} Options',
    'optionsMultipleSelection': '{{count}} Selected Items',

    'pickerTitle-default': 'File Picker',
    'pickerTitle-imagepicker': jahia_gwt_messages.label_imagepicker,
    'pickerTitle-editoriallinkpicker': jahia_gwt_messages.label_editorialpicker,
    'pickerTitle-filemanager-anthracite': jahia_gwt_messages.label_filemanager_title,
    'pickerTitle-editorialcontentmanager-anthracite': jahia_gwt_messages.label_editorialcontentmanager_title,
    'pickerTitle-portletmanager-anthracite': jahia_gwt_messages.label_portletmanager_title,
    'pickerTitle-repositoryexplorer-anthracite': jahia_gwt_messages.label_repositoryexplorer_title,
    'pickerTitle-categorymanager-anthracite': jahia_gwt_messages.label_categorymanager_title,
    'pickerTitle-sitemanager-anthracite': jahia_gwt_messages.label_sitemanager_title
});

Anthracite.dictionary.set("FR", {
    'autoRefresh': 'Rafraîchissement automatique',
    'jobs': 'Processus',
    'zeroTasks': 'Tableau de bord',
    'singleTask': 'Tableau de bord (%n% Tâche)',
    'multipleTasks': 'Tableau de bord (%n% Tâches)',
    'workflowType': '%n% Workflow type',
    'chooseWorkflowType': 'Choisir une workflow pour %n%:',
    'filterField': 'Filtrer',
    'sortBy': 'Sort By',
    'search': 'Rechercher dans %n%',
    'languageField': 'All Languages',
    'fromDate': 'From ...',
    'toDate': 'To ...',
    'dateRange': 'Date Range ...',
    'dateAnyTime': 'Any time',
    'dateCustom': 'Time range',
    'dateCustomLabel': 'Time range ...',
    'dateType': 'Par %n%',
    'allMetadata': 'All metadata',
    'ignoreMetadata': 'Ignore metadata',
    'metaLabel': 'Meta: %n%',
    'cancel': 'Annuler',
    'create': 'Créer',
    'save': 'Sauvegarder',
    'filterContent': 'Filtrer le contenu',
    'backgroundJobs': 'Tâches de fond',

    'previewPage': 'Aperçu',
    'previewSingleSelection': 'Aperçu',
    'previewMultipleSelection': 'Aperçu',

    'publishPage': 'Publier',
    'publishSingleSelection': 'Publier',
    'publishMultipleSelection': 'Publier',

    'optionsPage': 'Options de la page',
    'optionsSingleSelection': 'Options de {{node}}',
    'optionsMultipleSelection': '{{count}} éléments sélectionnés',

    'pickerTitle-default': 'File Picker',
    'pickerTitle-imagepicker': jahia_gwt_messages.label_imagepicker,
    'pickerTitle-editoriallinkpicker': jahia_gwt_messages.label_editorialpicker,
    'pickerTitle-filemanager-anthracite': jahia_gwt_messages.label_filemanager_title,
    'pickerTitle-editorialcontentmanager-anthracite': jahia_gwt_messages.label_editorialcontentmanager_title,
    'pickerTitle-portletmanager-anthracite': jahia_gwt_messages.label_portletmanager_title,
    'pickerTitle-repositoryexplorer-anthracite': jahia_gwt_messages.label_repositoryexplorer_title,
    'pickerTitle-categorymanager-anthracite': jahia_gwt_messages.label_categorymanager_title,
    'pickerTitle-sitemanager-anthracite': jahia_gwt_messages.label_sitemanager_title
});
