###############################################################################
package org.jahia.modules.social.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.slf4j.Logger
import java.util.Date
import org.jahia.services.content.*
import org.jahia.modules.social.*

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider
global SocialRuleService socialService
###############################################################################

rule "Create docspace activity"
   when
       A new node is created
	   - the node has the type jmix:docspace
   then
       Add activity "created" on node of types node.getTypes() for user user.getName() with messageKey "created.docspace"
end

rule "Create page activity"
   when
       A new node is created
	   - the node has the type jnt:page
   then
       Add activity "created" on node of types node.getTypes() for user user.getName() with messageKey "created.newpage"
end

rule "Create file in docspace activity"
   when
      The type jmix:docspaceFile has been assigned to a node
   then
       Add activity "created" on node of types node.getTypes() for user user.getName() with messageKey "created.docspacefile"
end

rule "Tagging activity"
   when
       A property j:newTag has been set on a node
        - the node has the type jmix:tagged
   then
       Add activity "tagged" on node of types node.getTypes() for user user.getName() with messageKey "tagged.node"
end

rule "Auto-split user activities node on creation"
	salience 101
	when
		A new node "activities" is created
		The node has a parent
			- the parent has the type jnt:user
   then
		Enable auto-splitting for subnodes of the node into folders of type jnt:contentList using configuration "date,jcr:created,yyyy;date,jcr:created,MM"
end

