###############################################################################
package org.jahia.modules.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.slf4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider
###############################################################################

rule "publish tags"
    when
       A new node is created
		- the node has the type jnt:tagList
    then
        Publish the node
end

rule "Tagging"
   when
       A property j:newTag has been set on a node
        - the node has the type jmix:tagged
   then
       Tag the node with the propertyValueAsString
end
