#created on: 20 dec. 2007
package org.jahia.services.content.rules

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import org.jahia.services.atmosphere.rules.*
import javax.jcr.observation.Event
import org.slf4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider
global SitePublisherSubscriberRuleService sitePubSubService

rule "Move subnodes to split folder"
    salience 100
    when
        The type jmix:autoSplitFolders has been assigned to a node
            - not in operation import
    then
        Move subnodes of node to split folder
end

rule "Move to split folder"
    salience 100
    when
        A new node is created
            - the parent has the type jmix:autoSplitFolders
            - not in operation import
    then
        Move to split folder node
end

rule "Send a site message on editorial content creation"
    salience 50
    when
        A new node is created
            - the node has the type jmix:editorialContent
    then
        Send site message "Content "+node.getName()+" has been created."
end


rule "Send a node message on editorial content update"
    salience 50
    when
        A property has been set on a node
            - the node has the type jmix:editorialContent
    then
        Send message "This page has been updated." to node channel
end