#created on: 20 dec. 2007
package org.jahia.services.content.automation

#list any import classes here.
import org.jahia.services.content.automation.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.apache.log4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider

rule "Metadata update / content created"
    salience -10
    no-loop
    when
        A new node is created
             - the node has the type mix:lastModified
             - the node has the type jmix:originWS
        The node has a parent
    then
        Set not existing property jcr:createdBy of the node with the name of the current user
        #Set the property jcr:created of the node with the current time
        Set the property j:originWS of the node with the value "live"
        Set not existing property jcr:lastModifiedBy of the parent with the name of the current user
        Set not existing property jcr:lastModified of the parent with the current time
        Get the ancestor "list" of type jnt:containerList
        Set not existing property jcr:lastModified of the list with the current time
        Set not existing property jcr:lastModifiedBy of the list with the name of the current user
        Get the ancestor "page" of type jnt:page
        Set not existing property jcr:lastModified of the page with the current time
        Set not existing property jcr:lastModifiedBy of the page with the name of the current user
end

rule "Metadata update / property modified"
    salience -11
    no-loop
    when
        A property has been set on a node
             - the node has the type mix:lastModified
        The property jcr:lastModified has not been modified yet on the node
    then
        Set not existing property jcr:lastModified of the node with the current time
        Set not existing property jcr:lastModifiedBy of the node with the name of the current user
        Get the ancestor "list" of type jnt:containerList
        Set not existing property jcr:lastModified of the list with the current time
        Set not existing property jcr:lastModifiedBy of the list with the name of the current user
        Get the ancestor "page" of type jnt:page
        Set not existing property jcr:lastModified of the page with the current time
        Set not existing property jcr:lastModifiedBy of the page with the name of the current user
end

rule "Metadata publication update / content validated"
    salience -10
    no-loop
    when
        A new node is created
             - the node has the type jmix:lastPublished
             - the node has the type jmix:originWS
        The node has a parent
        The node has a property j:originWS
             - the value is not "live"
    then
        Log "Publication event fired"
        Set and copy to staging the property j:lastPublishedBy of the node with the name of the current user
        Set and copy to staging the property j:lastPublished of the node with the current time
        Get the ancestor "list" of type jnt:containerList
        Set and copy to staging the property j:lastPublished of the list with the current time
        Set and copy to staging the property j:lastPublishedBy of the list with the name of the current user
        Get the ancestor "page" of type jnt:page
        Set and copy to staging the property j:lastPublished of the page with the current time
        Set and copy to staging the property j:lastPublishedBy of the page with the name of the current user
end

rule "Metadata publication update / property modified"
    salience -11
    no-loop
    when
        A property has been set on a node
             - the node has the type jmix:lastPublished
             - the node has the type jmix:originWS
        The property j:lastPublished has not been modified yet on the node
        The property j:originWS has not the value "live" on the node
    then
        Log "Publication event fired"    
        Set and copy to staging the property j:lastPublishedBy of the node with the name of the current user
        Set and copy to staging the property j:lastPublished of the node with the current time
        Get the ancestor "list" of type jnt:containerList
        Set and copy to staging the property j:lastPublished of the list with the current time
        Set and copy to staging the property j:lastPublishedBy of the list with the name of the current user
        Get the ancestor "page" of type jnt:page
        Set and copy to staging the property j:lastPublished of the page with the current time
        Set and copy to staging the property j:lastPublishedBy of the page with the name of the current user
end
