package org.jahia.services.content.rules.extraction

#list any import classes here.
import org.jahia.services.content.rules.*
import org.jahia.services.content.*
import javax.jcr.observation.Event
import org.slf4j.Logger

expander rules.dsl

#declare any global variables here
global User user
global Service service
global ImageService imageService
global ExtractionService extractionService
global Logger logger
global JCRStoreProvider provider

rule "Properties extraction"
#Extract all possible data from a file when it's uploaded
    salience 10
    when
        A file content has been modified
    then
        LogDebug "Properties extraction fired for node " + contentnode.getPath() 
        Extract properties from the file
end

rule "Set corresponding property with the value of the extracted metadata"
    salience 10
    when
        A file content has been modified
        A well known metadata field has been extracted
    then
        LogDebug "Setting extracted metadata field '" + metadata.getName() + "' with value '" + metadata.getValue() + "' as the property [" + metadata.getCorrespondingNodeTypeName() + "].[" + metadata.getCorrespondingPropertyName() + "] for node " + node.getPath()   
        Set corresponding property with the value of the extracted metadata
end