htmlFiltering:
  protocols:
    - http
    - https
  attributes:
    - name: class
      pattern: "(myclass1|myclass2)"
    - name: dir
    - name: hidden
    - name: id
      pattern: HTML_ID
    - name: lang
    - name: role
    - name: style
    - name: title
    - name: align
      elements: caption, col, colgroup, hr, img, table, tbody, td, tfoot, th, thead, tr
    - name: alt
      elements: img
    - name: autoplay, controls, loop, muted, preload
      elements: audio, video
    - name: cite
      elements: blockquote, del, ins, q
    - name: colspan, rowspan
      elements: td, th
    - name: crossorigin
      elements: audio, img, source, video
    - name: datetime
      elements: del, ins, time
    - name: disabled
      elements: button
    - name: download
      elements: a
    - name: headers
      elements: td, th
    - name: height, width
      pattern: NUMBER_OR_PERCENT
      elements: canvas, img, table, td, th, col, colgroup, video
    - name: href
      pattern: ONSITE_URL
      elements: a
    - name: hreflang
      elements: a
    - name: kind
      elements: track
    - name: label
      elements: track
    - name: media
      elements: a
    - name: rel
      elements: a
    - name: src
      elements: audio, img, source, track, video
    - name: srcset
      elements: img, source
    - name: summary
      elements: table
    - name: type
      elements: ol, ul
    - name: target
      elements: a, source
    - name: type
      elements: a, blockquote, button, col, del, ins, link, q
    - name: value
      elements: li
  elements:
    - name: h1, h2, h3, h4, h5, h6, hgroup, p, a, img, figure, figcaption, canvas, picture, br, strong, b, em, i, span, div, ul, ol, li, dl, dd, dt, table, tbody, thead, tfoot, tr, td, th, col, colgroup, caption, blockquote, q, cite, code, pre, var, abbr, address, del, s, details, summary, ins, sub, sup, small, mark, hr, button, legend, audio, video, source, track, nav, article, main, aside, section, time, header, footer, wbr
