drop sequence seq_audit_log;
create sequence seq_audit_log start with 1 increment by 20;
drop sequence seq_ctn_def;
create sequence seq_ctn_def start with 1 increment by 20;
drop sequence seq_ctn_def_properties;
create sequence seq_ctn_def_properties start with 1 increment by 20;
drop sequence seq_ctn_entries;
create sequence seq_ctn_entries start with 1 increment by 20;
drop sequence seq_ctn_lists;
create sequence seq_ctn_lists start with 1 increment by 20;
drop sequence seq_fields_data;
create sequence seq_fields_data start with 1 increment by 20;
drop sequence seq_fields_def;
create sequence seq_fields_def start with 1 increment by 20;
drop sequence seq_grps;
create sequence seq_grps start with 2 increment by 20;
drop sequence seq_link;
create sequence seq_link start with 1 increment by 20;
drop sequence seq_nstep_workflow;
create sequence seq_nstep_workflow start with 1 increment by 20;
drop sequence seq_nstep_workflowhistory;
create sequence seq_nstep_workflowhistory start with 1 increment by 20;
drop sequence seq_nstep_workflowinstance;
create sequence seq_nstep_workflowinstance start with 1 increment by 20;
drop sequence seq_nstep_workflowstep;
create sequence seq_nstep_workflowstep start with 1 increment by 20;
drop sequence seq_nstep_workflowuser;
create sequence seq_nstep_workflowuser start with 1 increment by 20;
drop sequence seq_pages_data;
create sequence seq_pages_data start with 1 increment by 20;
drop sequence seq_pages_def;
create sequence seq_pages_def start with 1 increment by 20;
drop sequence seq_pwd_policies;
create sequence seq_pwd_policies start with 1 increment by 20;
drop sequence seq_pwd_policy_rules;
create sequence seq_pwd_policy_rules start with 1 increment by 20;
drop sequence seq_pwd_policy_rule_params;
create sequence seq_pwd_policy_rule_params start with 1 increment by 20;
drop sequence seq_retrule;
create sequence seq_retrule start with 1 increment by 20;
drop sequence seq_retrule_range;
create sequence seq_retrule_range start with 1 increment by 20;
drop sequence seq_retruledef;
create sequence seq_retruledef start with 1 increment by 20;
drop sequence seq_site_lang_list;
create sequence seq_site_lang_list start with 1 increment by 20;
drop sequence seq_site_lang_maps;
create sequence seq_site_lang_maps start with 1 increment by 20;
drop sequence seq_sites;
create sequence seq_sites start with 1 increment by 20;
drop sequence seq_users;
create sequence seq_users start with 1 increment by 20;
drop sequence seq_version;
create sequence seq_version start with 1 increment by 20;
drop sequence seq_installedpatch;
create sequence seq_installedpatch start with 1 increment by 20;
drop sequence seq_subscriptions;
create sequence seq_subscriptions start with 1 increment by 20;
