name: Docker images cleanup

# The official GitHub image has not been updated for 2 years, and is not compatible
# with multi-arch images. See: https://github.com/actions/delete-package-versions/issues/90#issuecomment-2023951984
# This action was suggested as an alternative: https://github.com/dataaxiom/ghcr-cleanup-action

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  cleanup:
    name: Remove old Docker images
    runs-on: ubuntu-latest
    steps:
      # Image: jahia-ee-dev
      # Delete all images not attached to a tag
      # Delete images older than 1 month if they are 
      - uses: dataaxiom/ghcr-cleanup-action@244b3e8a35c266981a44b7e35da0c0e6a29b48a0 # Current main
        with:
          token: ${{ secrets.GH_PACKAGES_TOKEN }}
          owner: jahia
          repository: jahia-private
          packages: jahia-core-dev
          exclude-tags: '^\d+\.\d+\.\d+\.\d+(-SNAPSHOT)?$'
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
          older-than: 1 month
          validate: true
          dry-run: false