# Used to trigger a next-development version build during release time as a release dependency.
# Since it's used during release, we only need to do the build step and deploy to maven and skip the rest.

name: Release on api call

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jahia_version: ${{ steps.tags.outputs.jahia_version }}
      image_tag: ${{ steps.tags.outputs.image_tag }}
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: jahia-default-maven-m2-cache
      - name: Save/Restore build artifacts from cache
        uses: actions/cache@v4
        with:
          key: run-${{ github.run_id }}
          path: |
            ./**/target/**
      - name: Set environment variables from parameters
        shell: bash
        run: |
          echo "NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }}" >> $GITHUB_ENV
          echo "NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Store project version
        shell: bash
        run: mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec > jahia.version
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
      - name: Determine tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            cp jahia.version image.tag
          else
            echo `cat jahia.version`-pr-${{ github.event.pull_request.number }} > image.tag
          fi
      - id: tags
        name: Set Output variables
        run: |
          echo "::set-output name=jahia_version::`cat jahia.version`"
          echo "::set-output name=image_tag::`cat image.tag`"
      - name: Display Output variables
        run: |
          echo "OUTPUT: jahia_version = ${{steps.tags.outputs.jahia_version}}"
          echo "OUTPUT: image_tag = ${{steps.tags.outputs.image_tag}}"
      - name: mvn clean deploy
        shell: bash
        run: mvn -s .github/maven.settings.xml -e -Dimage.tag=${{steps.tags.outputs.image_tag}} clean deploy de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Pgwt-production,unit-tests,docker,docker-core-plugin -Dbamboo.buildNumber=${{ github.run_id }}
      - name: Compile GWT development
        shell: bash
        run: |
          cd gwt/
          mvn -s ../.github/maven.settings.xml -e \
            -Dimage.tag=${{steps.tags.outputs.image_tag}} \
            clean deploy \
            -Pgwt-development \
            -Dbamboo.buildNumber=${{ github.run_id }}
      - name: Generate Docker shorthand tags
        uses: fgerthoffert/actions-docker-shorthand-tags@main
        with:
          src_registry: github
          src_repository: jahia/jahia-core-dev
          src_username: ${{ github.actor }}
          src_secret: ${{ secrets.GITHUB_TOKEN }}
          dst_registry: github
          dst_repository: jahia/jahia-core-dev
          dst_username: ${{ github.actor }}
          dst_secret: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
      - uses: jahia/jahia-modules-action/slack-jahia@v2
        if: ${{ failure() }}
        with:
          job-event: "fail"
          skip-docker: true
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_TEAM_PRODUCT_SNAPSHOTS_NOTIFICATIONS }}
