# This action generates fresh m2 cache to be used as a fall back restore key
# https://github.com/actions/cache
name: Warmup maven m2 cache

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  cache-cleanup:
    name: Cleanup and refresh the m2 cache
    runs-on: ubuntu-latest
    steps:
      # Delete the previous version of the cache
      - uses: snnaplab/delete-branch-cache-action@20f7992a7b8b51aa719420d11b32c9d34a5eb362 # v1.0.0
        with:
          key: jahia-default-maven-m2-cache
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Generate cache with restore key jahia-default-maven-m2-cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.m2/repository
          key: jahia-default-maven-m2-cache
      - name: Set environment variables from parameters
        shell: bash
        run: |
          echo "NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }}" >> $GITHUB_ENV
          echo "NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}" >> $GITHUB_ENV          
      - name: Fetch build dependencies
        shell: bash
        run: |
          mvn -U -ntp -s .github/maven.settings.xml -Dmaven.resolver.transport=wagon de.qaware.maven:go-offline-maven-plugin:resolve-dependencies dependency:resolve
